### ISSUE TITLE
Aquamacs path makes configure fail

### ISSUE THREAD

**Issue by fakedrake** [rocky/emacs-test-simple#5]
Aquamacs does not play very well with symlinking executables so especially if the installation process is hidden by el-get the solution is non-trivial. Namely I managed to get it to work by runnung

    (setenv "EMACS" "<home-directory>/Applications/Aquamacs.app/Contents/MacOS/bin/Aquamacs")

It would be nice mention this in the readme or something

**Comment by rocky** [comment]
Would you place add this to the [Wiki](https://github.com/rocky/emacs-test-simple/wiki)?  Perhaps under a section on Aquamacs.

**Comment by rocky** [comment]
I don't understand or see where the _configure_ script s symlinking excecutables. More detail please.
